// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn9vlOP0ouYs3ZkDt5UYW0PqoEXIOzsw8',
    appId: '1:787625827594:web:69421b6babf581a82eaef3',
    messagingSenderId: '787625827594',
    projectId: 'advanced-diray-app',
    authDomain: 'advanced-diray-app.firebaseapp.com',
    storageBucket: 'advanced-diray-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ROY95IJLLUjG_hIAKwkhd8aszt9UwN8',
    appId: '1:787625827594:android:62c44e107c2cbee42eaef3',
    messagingSenderId: '787625827594',
    projectId: 'advanced-diray-app',
    storageBucket: 'advanced-diray-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR1AQ8i_umJHngExmyIPciwwQyScU3UkY',
    appId: '1:787625827594:ios:93a137de50a979302eaef3',
    messagingSenderId: '787625827594',
    projectId: 'advanced-diray-app',
    storageBucket: 'advanced-diray-app.firebasestorage.app',
    iosClientId: '787625827594-nu9fkokm9obk5cmsbpicg5l3lbudajg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedDiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR1AQ8i_umJHngExmyIPciwwQyScU3UkY',
    appId: '1:787625827594:ios:93a137de50a979302eaef3',
    messagingSenderId: '787625827594',
    projectId: 'advanced-diray-app',
    storageBucket: 'advanced-diray-app.firebasestorage.app',
    iosClientId: '787625827594-nu9fkokm9obk5cmsbpicg5l3lbudajg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedDiaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn9vlOP0ouYs3ZkDt5UYW0PqoEXIOzsw8',
    appId: '1:787625827594:web:83dcec4fd13d23b82eaef3',
    messagingSenderId: '787625827594',
    projectId: 'advanced-diray-app',
    authDomain: 'advanced-diray-app.firebaseapp.com',
    storageBucket: 'advanced-diray-app.firebasestorage.app',
  );

}